version: "3"
    
services:
    
    mysql:
        
        image: mysql:5.6
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysqlroot123
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wpuser123
        volumes:
            - mysql-data:/var/lib/mysql 
        networks:
            - wpnet
            
    wordpress:
    
        image: wordpress:latest
        container_name: wordpress
        environment:
            WORDPRESS_DB_HOST: mysql 
            WORDPRESS_DB_USER: wpuser 
            WORDPRESS_DB_PASSWORD: wpuser123 
            WORDPRESS_DB_NAME: wordpress 
        volumes:
            - wordpress-data:/var/www/html 
        networks:
            - wpnet
        ports:
            - "80:80"
networks:
    wpnet:
        
volumes:
    
    wordpress-data:
    mysql-data:
